// src/routes/+page.svelte
<script lang="ts">
	import { Calendar1, CalendarDays, Inbox } from 'lucide-svelte';
	import type { LayoutData } from './$types';
	import '../app.css';
	import Todo from '../components/Todo.svelte';
	import Shortcut from '../components/Shortcut.svelte';
	import Input from '../components/Input.svelte';

	let { data, children }: { data: LayoutData; children: Snippet } = $props();

	console.log(data);
</script>

<svelte:head>
	<title>Home</title>
	<meta name="description" content="Svelte demo app" />
</svelte:head>

<div class="flex min-h-screen grow flex-row">
	<div class="container mx-auto space-y-8 pt-8">
		<form method="post">
			<Input name="title" placeholder="Create">
				<Shortcut slot="postfix">SPACE</Shortcut>
			</Input>

			<div class="@container">
				<div class="grid grid-cols-2 @sm:grid-cols-4">
					<span>Project</span>
					<span>Tags</span>
					<span>Due</span>
					<span>Priority</span>
				</div>
			</div>

			<button type="submit">Add</button>
		</form>

		<div class="space-y-2">
			{#each data.todos as todo}
				<p>todo</p>
				<Todo id={todo.id} title={todo.title} />
			{/each}
		</div>
	</div>

	{#if data.selected}
		<div class="container mx-auto border-l border-slate-200 pt-8 shadow-lg">
			<div class="divide-y">
				<form method="post" action="/update">
					<label>
						<input type="checkbox" />
						Done
					</label>
				</form>
				<p class="text-xl font-semibold">{data.selected.title}</p>
			</div>
		</div>
	{/if}
</div>

// packages/app/routes/index.tsx
import { Handlers, PageProps } from "$fresh/server.ts";
import * as mod from "@mainframe-api/deno-sqlite";
import { Button } from "~/components/Button.tsx";
import { Input } from "~/components/Input.tsx";
import { Partial } from "$fresh/runtime.ts";
import { Todo } from "~/components/Todo.tsx";
import { Dialog } from "~/components/Dialog.tsx";
import { useSignal } from "@preact/signals";
import { Shortcut } from "~/components/Shortcut.tsx";

interface Data {
  results: string[];
  query: string;
}

// const db = new mod.DB("test.db");

// db.execute(`
//   DROP TABLE IF EXISTS tasks;
//   DROP TABLE IF EXISTS projects;

//   CREATE TABLE IF NOT EXISTS tasks (
//     id INTEGER PRIMARY KEY AUTOINCREMENT,
//     title TEXT
//   );
// CREATE TABLE IF NOT EXISTS projects (
//   id INTEGER PRIMARY KEY AUTOINCREMENT,
//   title TEXT
// );
// `);

// Run a simple query
// for (const name of ["Peter Parker", "Clark Kent", "Bruce Wayne"]) {
//   db.query("INSERT INTO people (name) VALUES (?)", [name]);
// }

// db.close();

export const handler: Handlers<Data> = {
  GET(req, ctx) {
    const db = new mod.DB("test.db");
    const url = new URL(req.url);
    const query = url.searchParams.get("selected") || "";
    const results = db.query("SELECT id, title FROM tasks");
    const selected = db.query("SELECT id, title FROM tasks WHERE id = ?", [
      query,
    ]);

    db.close();

    return ctx.render({ results, selected, query });
  },

  async POST(req, ctx) {
    const db = new mod.DB("test.db");
    const form = await req.formData();
    const title = form.get("title")?.toString();

    db.query("INSERT INTO tasks (title) VALUES (?)", [title]);
    const results = db.query("SELECT id, title FROM tasks");

    db.close();

    return ctx.render({ results, query: "" });
  },
};

export default function Dashboard({ data }: PageProps<Data>) {
  const { results, selected, query } = data;

  return (
    <>
      <div className="flex flex-row grow min-h-screen" f-client-nav>
        <div className="space-y-8 pt-8 container mx-auto">
          <form method="post">
            <Input
              name="title"
              placeholder="Create"
              postfix={<Shortcut>SPACE</Shortcut>}
            />

            <div className="@container">
              <div class="grid grid-cols-2 @sm:grid-cols-4">
                <span>Project</span>
                <span>Tags</span>
                <span>Due</span>
                <span>Priority</span>
              </div>
            </div>

            <button type="submit">Add</button>
          </form>

          <div className="space-y-2">
            <Partial name="todos">
              {results.map(([id, todo]) => <Todo id={id} title={todo} />)}
            </Partial>
          </div>
        </div>

        <Partial name="selected">
          {selected?.length > 0 && (
            <>
              <div className="pt-8 border-l border-slate-200 container mx-auto shadow-lg">
                <div className="divide-y">
                  <form method="post" action="/update">
                    <label>
                      <input type="checkbox" />
                      Done
                    </label>
                  </form>
                  <p className="text-xl font-semibold">
                    {selected ? selected[0] : ""}
                  </p>
                </div>
              </div>
            </>
          )}
        </Partial>
      </div>
    </>
  );
}
