// packages/app/components/Input.tsx
import { FunctionComponent, h } from "preact";
import { JSX } from "preact";

export const Input: FunctionComponent<
  JSX.HTMLAttributes<HTMLInputElement> & { postfix: string }
> = (
  props,
) => {
  return (
    <div class="relative input">
      <input {...props} />
      <span class="absolute right-3 top-1/2 -translate-y-1/2">
        {props.postfix}
      </span>
    </div>
  );
};

// src/components/Input.svelte
<script lang="ts">
	const props = $props();

	let inputRef;

	export function focus() {
		inputRef?.focus();
	}
</script>

<div class="input relative">
	<input bind:this={inputRef} {...props} />
	<span class="absolute right-3 top-1/2 -translate-y-1/2">
		<slot name="postfix"></slot>
	</span>
</div>
